### ISSUE TITLE
Bell[3] y Bell[7]

### ISSUE THREAD

**Issue by davidphysdavalos** [carlospgmat03/libs#12]
Creo que no funcionan bien, lo cheque con StateToDirac y da separable para Bell[3]

**Comment by carlospgmat03** [comment]
Hey Davalos, que bueno que intentamos este medio para corregir los bugs. No entiendo poruqe usas StateToDirac, si eso es para qubits, mientras uqe Bell[3] te daria un qutrit. lo mismo Bell[7]. Quiza seria bueno poner en StateToDirac qeu si la dimensoin no es potencia de dos, se queje.

**Comment by davidphysdavalos** [comment]
Ha!, ya!, confundi con GHZ, ooops!
